name: drive_ledger
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.2 # Tu SDK está bien definido aquí

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  dio: ^5.8.0+1
  flutter_secure_storage: ^9.2.4
  flutter_dotenv: ^5.2.1
  solana_wallet_adapter: ^0.1.5
  solana_web3: ^0.1.3
  bs58: # Considera especificar una versión aquí, ej: ^1.0.3
  pinenacl: ^0.6.0 # Esto está bien aquí, pub usará el override de todas formas
  app_links: ^3.4.3
  url_launcher: # Considera especificar una versión aquí, ej: ^6.0.0
  google_fonts: ^6.2.1
  firebase_core: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # dependency_overrides NO VA AQUÍ

# ESTA ES LA UBICACIÓN CORRECTA PARA dependency_overrides
dependency_overrides:
  pinenacl: ^0.6.0

flutter:
  uses-material-design: true
  ## habilitemos el .env
  assets:
    - .env
    - assets/images/
  # assets:
  #   - images/a_dot_burr.jpeg
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf