// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRM5zpjJjv2Irz4hx4L7KAbnQbARcIHY4',
    appId: '1:229147458065:web:7f6f713449a9f110f40fb0',
    messagingSenderId: '229147458065',
    projectId: 'drive-ledger',
    authDomain: 'drive-ledger.firebaseapp.com',
    storageBucket: 'drive-ledger.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg1kmOHvxwrB7X_kykOHgZONbRgRtHFzI',
    appId: '1:229147458065:android:ff9a921f588496acf40fb0',
    messagingSenderId: '229147458065',
    projectId: 'drive-ledger',
    storageBucket: 'drive-ledger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1LgF1PTu76QG_Nmia0MLyTjWMBbi_9sY',
    appId: '1:229147458065:ios:3da63db6c34152e5f40fb0',
    messagingSenderId: '229147458065',
    projectId: 'drive-ledger',
    storageBucket: 'drive-ledger.firebasestorage.app',
    iosBundleId: 'com.example.driveLedger',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1LgF1PTu76QG_Nmia0MLyTjWMBbi_9sY',
    appId: '1:229147458065:ios:3da63db6c34152e5f40fb0',
    messagingSenderId: '229147458065',
    projectId: 'drive-ledger',
    storageBucket: 'drive-ledger.firebasestorage.app',
    iosBundleId: 'com.example.driveLedger',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBRM5zpjJjv2Irz4hx4L7KAbnQbARcIHY4',
    appId: '1:229147458065:web:dee2c60153e89f89f40fb0',
    messagingSenderId: '229147458065',
    projectId: 'drive-ledger',
    authDomain: 'drive-ledger.firebaseapp.com',
    storageBucket: 'drive-ledger.firebasestorage.app',
  );
}
